/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "intex adapter settings": {
        en: "Adapter settings for intex",
        de: "Adaptereinstellungen für intex",
        ru: "Настройки адаптера для intex",
        pt: "Configurações do adaptador para intex",
        nl: "Adapterinstellingen voor intex",
        fr: "Paramètres d'adaptateur pour intex",
        it: "Impostazioni dell'adattatore per intex",
        es: "Ajustes del adaptador para intex",
        pl: "Ustawienia adaptera dla intex",
        "uk": "налаштування адаптера intex",
        "zh-cn": "intex的适配器设置",
    },
    "App Email": {
        en: "App Email",
        de: "App-E-Mail",
        ru: "Электронная почта приложения",
        pt: "Email do aplicativo",
        nl: "App-e-mail",
        fr: "Courriel de l'application",
        it: "E-mail dell'app",
        es: "Correo electrónico de la aplicación",
        pl: "E-mail aplikacji",
        "uk": "Електронна пошта",
        "zh-cn": "应用电子邮件",
    },
    "App Password": {
        en: "App Password",
        de: "App-Passwort",
        ru: "Пароль приложения",
        pt: "Senha de app",
        nl: "App-wachtwoord",
        fr: "Mot de passe de l'application",
        it: "Password dell'app",
        es: "Contraseña de la aplicación",
        pl: "Hasło do aplikacji",
        "uk": "Ім'я користувача",
        "zh-cn": "应用密码",
    },
    "Update interval (in minutes)": {
        en: "Update interval (in minutes)",
        de: "Aktualisierungsintervall (in Minuten)",
        ru: "Интервал обновления (в минутах)",
        pt: "Intervalo de atualização (em minutos)",
        nl: "Update-interval (in minuten)",
        fr: "Intervalle de mise à jour (en minutes)",
        it: "Intervallo di aggiornamento (in minuti)",
        es: "Intervalo de actualización (en minutos)",
        pl: "Interwał aktualizacji (w minutach)",
        "uk": "Проміжок оновлення (в хвилини)",
        "zh-cn": "更新间隔（分钟）",
    },
    "Pool device address": {
        "en": "Pool device address",
        "de": "Adresse des Poolgerätes",
        "ru": "Адрес устройства для бассейна",
        "pt": "Endereço do dispositivo da associação",
        "nl": "Pool",
        "fr": "Adresse de l ' appareil de bord",
        "it": "Indirizzo del dispositivo della piscina",
        "es": "Dirección del dispositivo de la piscina",
        "pl": "Adres Poolu",
        "uk": "Статус на сервери",
        "zh-cn": "D. 车辆处理"
    },
    "Pool port address": {
        "en": "Pool port address",
        "de": "Adresse des Hafens",
        "ru": "Адрес порта бассейна",
        "pt": "Endereço da porta da piscina",
        "nl": "Pool Port",
        "fr": "Adresse du port de la piscine",
        "it": "Indirizzo della porta della piscina",
        "es": "Dirección portuaria de piscina",
        "pl": "Port",
        "uk": "Карта сайту",
        "zh-cn": "Pool港口地址"
    },
    "find pools": {
        "en": "find pools",
        "de": "Pools finden",
        "ru": "найти бассейны",
        "pt": "encontrar piscinas",
        "nl": "zoek zwembaden",
        "fr": "trouver des piscines",
        "it": "trovare piscine",
        "es": "encontrar piscinas",
        "pl": "zbiornik",
        "uk": "знайти басейни",
        "zh-cn": "寻找人才库"
    },
    "The strategy of how to communicate with the pool and the cloud": {
        "en": "The strategy of how to communicate with the pool and the cloud",
        "de": "Die Strategie, wie man mit dem Pool und der Cloud kommunizieren kann",
        "ru": "Стратегия как общаться с бассейном и облаком",
        "pt": "A estratégia de como se comunicar com a piscina e a nuvem",
        "nl": "De strategie om te communiceren met het zwembad en de wolk",
        "fr": "La stratégie de communication avec la piscine et le nuage",
        "it": "La strategia di come comunicare con la piscina e il cloud",
        "es": "La estrategia de cómo comunicarse con la piscina y la nube",
        "pl": "Strategia komunikacji z basenem i chmurą",
        "uk": "Стратегія спілкування з басейном і хмарою",
        "zh-cn": "如何与该集合和云雾传播战略"
    },
    "Cloud secondary; Pool local if available": {
        "en": "Cloud secondary; Pool local if available",
        "de": "Cloud sekundär; Pool lokal, falls vorhanden",
        "ru": "Облачные вторичные; Бассейн местный если доступный",
        "pt": "Secundário da nuvem; Piscina local se disponível",
        "nl": "Cloud secundaire; Pool lokaal",
        "fr": "Cloud secondaire; Piscine locale si disponible",
        "it": "Nuvola secondaria; Piscina locale se disponibile",
        "es": "Cloud secondary; Piscina local si está disponible",
        "pl": "Chmury wtórne Poolnie, jeśli jest dostępne",
        "uk": "Хмар вторинний; Басейн місцевий, якщо є",
        "zh-cn": "Cloud 其次; 地方"
    },
    "Cloud secondary; Pool only local": {
        "en": "Cloud secondary; Pool only local",
        "de": "Cloud sekundär; Pool nur lokal",
        "ru": "Облачные вторичные; Бассейн только местный",
        "pt": "Secundário da nuvem; Piscina apenas local",
        "nl": "Cloud secundaire; Pool",
        "fr": "Cloud secondaire; Piscine seulement locale",
        "it": "Nuvola secondaria; Piscina solo locale",
        "es": "Cloud secondary; Piscina sólo local",
        "pl": "Chmury wtórne Lokalnie",
        "uk": "Хмар вторинний; Басейн тільки місцевий",
        "zh-cn": "Cloud 其次; 仅当地"
    },
    "Only cloud": {
        "en": "Only cloud",
        "de": "Nur Cloud",
        "ru": "Только облако",
        "pt": "Apenas nuvem",
        "nl": "♪",
        "fr": "Seulement nuage",
        "it": "Solo cloud",
        "es": "Sólo nube",
        "pl": "Tylko chmury",
        "uk": "Невелика хмарність",
        "zh-cn": "只剩下阴影"
    },
    "Only local": {
        "en": "Only local",
        "de": "Nur lokal",
        "ru": "Только местные",
        "pt": "Apenas local",
        "nl": "Alleen",
        "fr": "Seulement local",
        "it": "Solo locali",
        "es": "Sólo local",
        "pl": "Tylko lokalny",
        "uk": "Тільки локальні",
        "zh-cn": "只在地方"
    }
};
